version: "3.7"

services:
  mockupdd:
    container_name: mockupdd
    build: . # use this, if you change the dockerfile
    tty: true
    ports:
      - "0.0.0.0:8001:8000"
    volumes:
      - .:/usr/src/app/
    networks:
      - mockupdd
    command: ["/start.sh"]

networks:
  mockupdd:
    name: mockupdd
    driver: bridge
